### ISSUE TITLE
DBテスト：Node.JS起動時/再起動時の処理

### ISSUE THREAD

**Issue by maccostar** [hackersjail/mugensweeper#127]
## テスト対象
FieldHistory/BombHistoryからレコードを全件取得してStore上でFieldを作成する機能に関するテスト

## テストの概要

- 複数手が再現できること
　Given）FieldHistory/BombHistoryを数手分作成する
　Given）答えとなるField/BombMapを作成する
　Then）関数が作成したField/BombMapが答えと一致するかを確認する

### 親課題

---
#126 

#### 備考

---

### テンプレート参考

---

**Comment by dmiyamoto** [comment]
対応が完了したようなので、当issueはクローズします。
