### ISSUE TITLE
APIテスト：GET Fieldリクエスト時の動作

### ISSUE THREAD

**Issue by maccostar** [hackersjail/mugensweeper#130]
## テストの目的
ユーザからのGet Fieldリクエストに応じて、必要なFieldの情報を返却できているかのテスト

## テスト概要
- Store上のFinalActions情報が30分以内になっていること
- ユーザに渡すField情報がFinalActions情報に応じて編集されている
- swaggerの実装

### 親課題

---
#126 

### 備考

---

**Comment by dmiyamoto** [comment]
対応が対応が完了したようなので、当issueはクローズします。
