### ISSUE TITLE
#130の実装（GET Fieldリクエスト時の動作）

### ISSUE THREAD

**Issue by maccostar** [hackersjail/mugensweeper#131]
## 概要
1. Store上のField情報を全件取得する
2. Store上のFinalActions情報から30分以内のレコードを取得する
3. 取得したField情報をユーザに提供できる形に編集する
 3-1. Field情報のxかつyが、2で取得したFinalActionsの情報のxかつyと一致しない場合は、ユーザに渡すField情報からuserIdを削除する

## 変更点
- 変更点1
- 変更点2

### 親課題

---
要件 #126 
テスト #130 

### 備考

---

**Comment by dmiyamoto** [comment]
対応が完了したようなので、当issueはクローズします。
