### ISSUE TITLE
ユーザー情報に関する要件整理

### ISSUE THREAD

**Issue by maccostar** [hackersjail/mugensweeper#132]
## 概要
- GET Userリクエストをもらったら、ユーザの名前を登録する
- ユーザーIDを作成する
- ユーザ名+ユーザーIDをフロントに返す

## 変更点
- ユーザ名の書式をチェックする（テスト #95 / 実装 #101 ）
- DBからユーザIDを全件取得する（テスト #96 / 実装 #102 ）
- ユーザIDを作成する（テスト #98/実装 #103 ）
- ユーザ情報をDBに登録する（テスト #99/実装 #104）

### 親課題

---
なし

#### 備考

---

**Comment by dmiyamoto** [comment]
りょうこさん対応済みのため、当issueをcloseします。
