### ISSUE TITLE
APIテスト：ユーザーIDのユニークチェック、書式チェック

### ISSUE THREAD

**Issue by maccostar** [hackersjail/mugensweeper#98]
（実装側で、ユーザーIDが既存のもの重複しなくなるまで生成し直すロジックを想定）
- DBから全件取得した既存のユーザーIDと重複していない
- 文字数が指定内であるか（8文字以下）
- 文字種に大文字、小文字、ハイフン、アンスコ以外が使われていないか

**Comment by dmiyamoto** [comment]
りょうこさん対応済みのため、当issueをcloseします。
